# Generated by Django 6.0.1 on 2026-01-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier'), ('admin', 'Admin'), ('delivery', 'Delivery Personnel')], default='customer', max_length=20),
        ),
    ]
