# Generated by Django 6.0.1 on 2026-01-17 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontendImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='frontend_images/')),
                ('image_type', models.CharField(choices=[('banner', 'Banner'), ('hero', 'Hero Image'), ('slide', 'Slider Image'), ('promo', 'Promotional Image'), ('other', 'Other')], default='other', max_length=20)),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=255)),
                ('link_url', models.URLField(blank=True, help_text='Optional link when image is clicked', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Frontend Image',
                'verbose_name_plural': 'Frontend Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
